#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("LegacyBar.Sample.Resource", IsApplication=true)]

namespace LegacyBar.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
			LegacyBar.Library.Resource.Attribute.background = LegacyBar.Sample.Resource.Attribute.background;
			LegacyBar.Library.Resource.Attribute.background_item = LegacyBar.Sample.Resource.Attribute.background_item;
			LegacyBar.Library.Resource.Attribute.is_bottom = LegacyBar.Sample.Resource.Attribute.is_bottom;
			LegacyBar.Library.Resource.Attribute.light_icons = LegacyBar.Sample.Resource.Attribute.light_icons;
			LegacyBar.Library.Resource.Attribute.separator = LegacyBar.Sample.Resource.Attribute.separator;
			LegacyBar.Library.Resource.Attribute.theme = LegacyBar.Sample.Resource.Attribute.theme;
			LegacyBar.Library.Resource.Attribute.title = LegacyBar.Sample.Resource.Attribute.title;
			LegacyBar.Library.Resource.Attribute.title_color = LegacyBar.Sample.Resource.Attribute.title_color;
			LegacyBar.Library.Resource.Color.Red = LegacyBar.Sample.Resource.Color.Red;
			LegacyBar.Library.Resource.Color.actionbar_accentcolor_black = LegacyBar.Sample.Resource.Color.actionbar_accentcolor_black;
			LegacyBar.Library.Resource.Color.actionbar_accentcolor_blue = LegacyBar.Sample.Resource.Color.actionbar_accentcolor_blue;
			LegacyBar.Library.Resource.Color.actionbar_accentcolor_darkgray = LegacyBar.Sample.Resource.Color.actionbar_accentcolor_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_accentcolor_lightgray = LegacyBar.Sample.Resource.Color.actionbar_accentcolor_lightgray;
			LegacyBar.Library.Resource.Color.actionbar_background_end = LegacyBar.Sample.Resource.Color.actionbar_background_end;
			LegacyBar.Library.Resource.Color.actionbar_background_end_alt = LegacyBar.Sample.Resource.Color.actionbar_background_end_alt;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end = LegacyBar.Sample.Resource.Color.actionbar_background_item_pressed_end;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end_alt = LegacyBar.Sample.Resource.Color.actionbar_background_item_pressed_end_alt;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start = LegacyBar.Sample.Resource.Color.actionbar_background_item_pressed_start;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start_alt = LegacyBar.Sample.Resource.Color.actionbar_background_item_pressed_start_alt;
			LegacyBar.Library.Resource.Color.actionbar_background_start = LegacyBar.Sample.Resource.Color.actionbar_background_start;
			LegacyBar.Library.Resource.Color.actionbar_background_start_alt = LegacyBar.Sample.Resource.Color.actionbar_background_start_alt;
			LegacyBar.Library.Resource.Color.actionbar_maincolor_black = LegacyBar.Sample.Resource.Color.actionbar_maincolor_black;
			LegacyBar.Library.Resource.Color.actionbar_maincolor_blue = LegacyBar.Sample.Resource.Color.actionbar_maincolor_blue;
			LegacyBar.Library.Resource.Color.actionbar_maincolor_darkgray = LegacyBar.Sample.Resource.Color.actionbar_maincolor_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_maincolor_lightgray = LegacyBar.Sample.Resource.Color.actionbar_maincolor_lightgray;
			LegacyBar.Library.Resource.Color.actionbar_pressedcolor_black = LegacyBar.Sample.Resource.Color.actionbar_pressedcolor_black;
			LegacyBar.Library.Resource.Color.actionbar_pressedcolor_blue = LegacyBar.Sample.Resource.Color.actionbar_pressedcolor_blue;
			LegacyBar.Library.Resource.Color.actionbar_pressedcolor_darkgray = LegacyBar.Sample.Resource.Color.actionbar_pressedcolor_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_pressedcolor_lightgray = LegacyBar.Sample.Resource.Color.actionbar_pressedcolor_lightgray;
			LegacyBar.Library.Resource.Color.actionbar_separator = LegacyBar.Sample.Resource.Color.actionbar_separator;
			LegacyBar.Library.Resource.Color.actionbar_separator_alt = LegacyBar.Sample.Resource.Color.actionbar_separator_alt;
			LegacyBar.Library.Resource.Color.actionbar_separator_black = LegacyBar.Sample.Resource.Color.actionbar_separator_black;
			LegacyBar.Library.Resource.Color.actionbar_separator_blue = LegacyBar.Sample.Resource.Color.actionbar_separator_blue;
			LegacyBar.Library.Resource.Color.actionbar_separator_darkgray = LegacyBar.Sample.Resource.Color.actionbar_separator_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_separator_lightgray = LegacyBar.Sample.Resource.Color.actionbar_separator_lightgray;
			LegacyBar.Library.Resource.Color.actionbar_title = LegacyBar.Sample.Resource.Color.actionbar_title;
			LegacyBar.Library.Resource.Color.actionbar_title_alt = LegacyBar.Sample.Resource.Color.actionbar_title_alt;
			LegacyBar.Library.Resource.Color.actionbar_title_black = LegacyBar.Sample.Resource.Color.actionbar_title_black;
			LegacyBar.Library.Resource.Color.actionbar_title_blue = LegacyBar.Sample.Resource.Color.actionbar_title_blue;
			LegacyBar.Library.Resource.Color.actionbar_title_darkgray = LegacyBar.Sample.Resource.Color.actionbar_title_darkgray;
			LegacyBar.Library.Resource.Color.actionbar_title_lightgray = LegacyBar.Sample.Resource.Color.actionbar_title_lightgray;
			LegacyBar.Library.Resource.Color.black = LegacyBar.Sample.Resource.Color.black;
			LegacyBar.Library.Resource.Color.blue = LegacyBar.Sample.Resource.Color.blue;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_end = LegacyBar.Sample.Resource.Color.bottomactionbar_background_end;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_end = LegacyBar.Sample.Resource.Color.bottomactionbar_background_item_pressed_end;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_start = LegacyBar.Sample.Resource.Color.bottomactionbar_background_item_pressed_start;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_start = LegacyBar.Sample.Resource.Color.bottomactionbar_background_start;
			LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_black = LegacyBar.Sample.Resource.Color.bottomactionbar_maincolor_black;
			LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_blue = LegacyBar.Sample.Resource.Color.bottomactionbar_maincolor_blue;
			LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_darkgray = LegacyBar.Sample.Resource.Color.bottomactionbar_maincolor_darkgray;
			LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_lightgray = LegacyBar.Sample.Resource.Color.bottomactionbar_maincolor_lightgray;
			LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_black = LegacyBar.Sample.Resource.Color.bottomactionbar_pressedcolor_black;
			LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_blue = LegacyBar.Sample.Resource.Color.bottomactionbar_pressedcolor_blue;
			LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_darkgray = LegacyBar.Sample.Resource.Color.bottomactionbar_pressedcolor_darkgray;
			LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_lightgray = LegacyBar.Sample.Resource.Color.bottomactionbar_pressedcolor_lightgray;
			LegacyBar.Library.Resource.Color.bottomactionbar_separator = LegacyBar.Sample.Resource.Color.bottomactionbar_separator;
			LegacyBar.Library.Resource.Color.bottomactionbar_title = LegacyBar.Sample.Resource.Color.bottomactionbar_title;
			LegacyBar.Library.Resource.Color.green = LegacyBar.Sample.Resource.Color.green;
			LegacyBar.Library.Resource.Color.grey = LegacyBar.Sample.Resource.Color.grey;
			LegacyBar.Library.Resource.Color.pager_black = LegacyBar.Sample.Resource.Color.pager_black;
			LegacyBar.Library.Resource.Color.pager_blue = LegacyBar.Sample.Resource.Color.pager_blue;
			LegacyBar.Library.Resource.Color.pager_darkgray = LegacyBar.Sample.Resource.Color.pager_darkgray;
			LegacyBar.Library.Resource.Color.pager_lightgray = LegacyBar.Sample.Resource.Color.pager_lightgray;
			LegacyBar.Library.Resource.Color.red = LegacyBar.Sample.Resource.Color.red;
			LegacyBar.Library.Resource.Color.white = LegacyBar.Sample.Resource.Color.white;
			LegacyBar.Library.Resource.Color.yellow = LegacyBar.Sample.Resource.Color.yellow;
			LegacyBar.Library.Resource.Dimension.actionbar_accentheight = LegacyBar.Sample.Resource.Dimension.actionbar_accentheight;
			LegacyBar.Library.Resource.Dimension.actionbar_height = LegacyBar.Sample.Resource.Dimension.actionbar_height;
			LegacyBar.Library.Resource.Dimension.actionbar_home_item_width = LegacyBar.Sample.Resource.Dimension.actionbar_home_item_width;
			LegacyBar.Library.Resource.Dimension.actionbar_item_height = LegacyBar.Sample.Resource.Dimension.actionbar_item_height;
			LegacyBar.Library.Resource.Dimension.actionbar_item_height_over = LegacyBar.Sample.Resource.Dimension.actionbar_item_height_over;
			LegacyBar.Library.Resource.Dimension.actionbar_item_height_overflow = LegacyBar.Sample.Resource.Dimension.actionbar_item_height_overflow;
			LegacyBar.Library.Resource.Dimension.actionbar_item_width = LegacyBar.Sample.Resource.Dimension.actionbar_item_width;
			LegacyBar.Library.Resource.Drawable.actionbar_back_indicator = LegacyBar.Sample.Resource.Drawable.actionbar_back_indicator;
			LegacyBar.Library.Resource.Drawable.actionbar_back_indicator_dark = LegacyBar.Sample.Resource.Drawable.actionbar_back_indicator_dark;
			LegacyBar.Library.Resource.Drawable.actionbar_background = LegacyBar.Sample.Resource.Drawable.actionbar_background;
			LegacyBar.Library.Resource.Drawable.actionbar_background_alt = LegacyBar.Sample.Resource.Drawable.actionbar_background_alt;
			LegacyBar.Library.Resource.Drawable.actionbar_background_black = LegacyBar.Sample.Resource.Drawable.actionbar_background_black;
			LegacyBar.Library.Resource.Drawable.actionbar_background_blue = LegacyBar.Sample.Resource.Drawable.actionbar_background_blue;
			LegacyBar.Library.Resource.Drawable.actionbar_background_darkgray = LegacyBar.Sample.Resource.Drawable.actionbar_background_darkgray;
			LegacyBar.Library.Resource.Drawable.actionbar_background_lightgray = LegacyBar.Sample.Resource.Drawable.actionbar_background_lightgray;
			LegacyBar.Library.Resource.Drawable.actionbar_btn = LegacyBar.Sample.Resource.Drawable.actionbar_btn;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_alt = LegacyBar.Sample.Resource.Drawable.actionbar_btn_alt;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_black = LegacyBar.Sample.Resource.Drawable.actionbar_btn_black;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_blue = LegacyBar.Sample.Resource.Drawable.actionbar_btn_blue;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_darkgray = LegacyBar.Sample.Resource.Drawable.actionbar_btn_darkgray;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_lightgray = LegacyBar.Sample.Resource.Drawable.actionbar_btn_lightgray;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_normal = LegacyBar.Sample.Resource.Drawable.actionbar_btn_normal;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_normal_alt = LegacyBar.Sample.Resource.Drawable.actionbar_btn_normal_alt;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed = LegacyBar.Sample.Resource.Drawable.actionbar_btn_pressed;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed_alt = LegacyBar.Sample.Resource.Drawable.actionbar_btn_pressed_alt;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background = LegacyBar.Sample.Resource.Drawable.bottomactionbar_background;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background_black = LegacyBar.Sample.Resource.Drawable.bottomactionbar_background_black;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background_blue = LegacyBar.Sample.Resource.Drawable.bottomactionbar_background_blue;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background_darkgray = LegacyBar.Sample.Resource.Drawable.bottomactionbar_background_darkgray;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background_lightgray = LegacyBar.Sample.Resource.Drawable.bottomactionbar_background_lightgray;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn = LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_black = LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn_black;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_blue = LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn_blue;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_darkgray = LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn_darkgray;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_lightgray = LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn_lightgray;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_normal = LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn_normal;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_pressed = LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn_pressed;
			LegacyBar.Library.Resource.Drawable.ic_action_overflow = LegacyBar.Sample.Resource.Drawable.ic_action_overflow;
			LegacyBar.Library.Resource.Drawable.ic_action_overflow_dark = LegacyBar.Sample.Resource.Drawable.ic_action_overflow_dark;
			LegacyBar.Library.Resource.Id.actionbar_actions = LegacyBar.Sample.Resource.Id.actionbar_actions;
			LegacyBar.Library.Resource.Id.actionbar_home = LegacyBar.Sample.Resource.Id.actionbar_home;
			LegacyBar.Library.Resource.Id.actionbar_home_bg = LegacyBar.Sample.Resource.Id.actionbar_home_bg;
			LegacyBar.Library.Resource.Id.actionbar_home_btn = LegacyBar.Sample.Resource.Id.actionbar_home_btn;
			LegacyBar.Library.Resource.Id.actionbar_home_is_back = LegacyBar.Sample.Resource.Id.actionbar_home_is_back;
			LegacyBar.Library.Resource.Id.actionbar_home_logo = LegacyBar.Sample.Resource.Id.actionbar_home_logo;
			LegacyBar.Library.Resource.Id.actionbar_item = LegacyBar.Sample.Resource.Id.actionbar_item;
			LegacyBar.Library.Resource.Id.actionbar_progress = LegacyBar.Sample.Resource.Id.actionbar_progress;
			LegacyBar.Library.Resource.Id.actionbar_title = LegacyBar.Sample.Resource.Id.actionbar_title;
			LegacyBar.Library.Resource.Id.actionbar_title_layout = LegacyBar.Sample.Resource.Id.actionbar_title_layout;
			LegacyBar.Library.Resource.Id.custom = LegacyBar.Sample.Resource.Id.custom;
			LegacyBar.Library.Resource.Id.holo_black = LegacyBar.Sample.Resource.Id.holo_black;
			LegacyBar.Library.Resource.Id.holo_blue = LegacyBar.Sample.Resource.Id.holo_blue;
			LegacyBar.Library.Resource.Id.holo_gray = LegacyBar.Sample.Resource.Id.holo_gray;
			LegacyBar.Library.Resource.Id.holo_light = LegacyBar.Sample.Resource.Id.holo_light;
			LegacyBar.Library.Resource.Id.overflow_spinner = LegacyBar.Sample.Resource.Id.overflow_spinner;
			LegacyBar.Library.Resource.Id.screen = LegacyBar.Sample.Resource.Id.screen;
			LegacyBar.Library.Resource.Layout.actionbar = LegacyBar.Sample.Resource.Layout.actionbar;
			LegacyBar.Library.Resource.Layout.actionbar_item = LegacyBar.Sample.Resource.Layout.actionbar_item;
			LegacyBar.Library.Resource.Layout.blankspinner = LegacyBar.Sample.Resource.Layout.blankspinner;
			LegacyBar.Library.Resource.Layout.overflowactionbar_item = LegacyBar.Sample.Resource.Layout.overflowactionbar_item;
			LegacyBar.Library.Resource.Layout.spinneritem = LegacyBar.Sample.Resource.Layout.spinneritem;
			LegacyBar.Library.Resource.String.actionbar_activity_not_found = LegacyBar.Sample.Resource.String.actionbar_activity_not_found;
			LegacyBar.Library.Resource.Style.MyTheme = LegacyBar.Sample.Resource.Style.MyTheme;
			LegacyBar.Library.Resource.Style.actionbar = LegacyBar.Sample.Resource.Style.actionbar;
			LegacyBar.Library.Resource.Style.actionbarhomeitem = LegacyBar.Sample.Resource.Style.actionbarhomeitem;
			LegacyBar.Library.Resource.Style.actionbarhomelogo = LegacyBar.Sample.Resource.Style.actionbarhomelogo;
			LegacyBar.Library.Resource.Style.actionbaritem = LegacyBar.Sample.Resource.Style.actionbaritem;
			LegacyBar.Library.Resource.Style.actionbarprogressbar = LegacyBar.Sample.Resource.Style.actionbarprogressbar;
			LegacyBar.Library.Resource.Style.clearbutton = LegacyBar.Sample.Resource.Style.clearbutton;
			LegacyBar.Library.Resource.Styleable.actionbar = LegacyBar.Sample.Resource.Styleable.actionbar;
			LegacyBar.Library.Resource.Styleable.actionbar_background = LegacyBar.Sample.Resource.Styleable.actionbar_background;
			LegacyBar.Library.Resource.Styleable.actionbar_background_item = LegacyBar.Sample.Resource.Styleable.actionbar_background_item;
			LegacyBar.Library.Resource.Styleable.actionbar_is_bottom = LegacyBar.Sample.Resource.Styleable.actionbar_is_bottom;
			LegacyBar.Library.Resource.Styleable.actionbar_light_icons = LegacyBar.Sample.Resource.Styleable.actionbar_light_icons;
			LegacyBar.Library.Resource.Styleable.actionbar_separator = LegacyBar.Sample.Resource.Styleable.actionbar_separator;
			LegacyBar.Library.Resource.Styleable.actionbar_theme = LegacyBar.Sample.Resource.Styleable.actionbar_theme;
			LegacyBar.Library.Resource.Styleable.actionbar_title = LegacyBar.Sample.Resource.Styleable.actionbar_title;
			LegacyBar.Library.Resource.Styleable.actionbar_title_color = LegacyBar.Sample.Resource.Styleable.actionbar_title_color;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int background = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int background_item = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int is_bottom = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int light_icons = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int separator = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int theme = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int title = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int title_color = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050039
			public const int Red = 2131034169;
			
			// aapt resource value: 0x7f050023
			public const int actionbar_accentcolor_black = 2131034147;
			
			// aapt resource value: 0x7f05002b
			public const int actionbar_accentcolor_blue = 2131034155;
			
			// aapt resource value: 0x7f05001b
			public const int actionbar_accentcolor_darkgray = 2131034139;
			
			// aapt resource value: 0x7f050013
			public const int actionbar_accentcolor_lightgray = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int actionbar_background_end = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int actionbar_background_end_alt = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int actionbar_background_item_pressed_end = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int actionbar_background_item_pressed_end_alt = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int actionbar_background_item_pressed_start = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int actionbar_background_item_pressed_start_alt = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int actionbar_background_start = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int actionbar_background_start_alt = 2131034120;
			
			// aapt resource value: 0x7f050022
			public const int actionbar_maincolor_black = 2131034146;
			
			// aapt resource value: 0x7f05002a
			public const int actionbar_maincolor_blue = 2131034154;
			
			// aapt resource value: 0x7f05001a
			public const int actionbar_maincolor_darkgray = 2131034138;
			
			// aapt resource value: 0x7f050012
			public const int actionbar_maincolor_lightgray = 2131034130;
			
			// aapt resource value: 0x7f050024
			public const int actionbar_pressedcolor_black = 2131034148;
			
			// aapt resource value: 0x7f05002c
			public const int actionbar_pressedcolor_blue = 2131034156;
			
			// aapt resource value: 0x7f05001c
			public const int actionbar_pressedcolor_darkgray = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int actionbar_pressedcolor_lightgray = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int actionbar_separator = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int actionbar_separator_alt = 2131034118;
			
			// aapt resource value: 0x7f050026
			public const int actionbar_separator_black = 2131034150;
			
			// aapt resource value: 0x7f05002e
			public const int actionbar_separator_blue = 2131034158;
			
			// aapt resource value: 0x7f05001e
			public const int actionbar_separator_darkgray = 2131034142;
			
			// aapt resource value: 0x7f050016
			public const int actionbar_separator_lightgray = 2131034134;
			
			// aapt resource value: 0x7f050001
			public const int actionbar_title = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int actionbar_title_alt = 2131034119;
			
			// aapt resource value: 0x7f050025
			public const int actionbar_title_black = 2131034149;
			
			// aapt resource value: 0x7f05002d
			public const int actionbar_title_blue = 2131034157;
			
			// aapt resource value: 0x7f05001d
			public const int actionbar_title_darkgray = 2131034141;
			
			// aapt resource value: 0x7f050015
			public const int actionbar_title_lightgray = 2131034133;
			
			// aapt resource value: 0x7f050033
			public const int black = 2131034163;
			
			// aapt resource value: 0x7f050036
			public const int blue = 2131034166;
			
			// aapt resource value: 0x7f05000f
			public const int bottomactionbar_background_end = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int bottomactionbar_background_item_pressed_end = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int bottomactionbar_background_item_pressed_start = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int bottomactionbar_background_start = 2131034126;
			
			// aapt resource value: 0x7f050027
			public const int bottomactionbar_maincolor_black = 2131034151;
			
			// aapt resource value: 0x7f05002f
			public const int bottomactionbar_maincolor_blue = 2131034159;
			
			// aapt resource value: 0x7f05001f
			public const int bottomactionbar_maincolor_darkgray = 2131034143;
			
			// aapt resource value: 0x7f050017
			public const int bottomactionbar_maincolor_lightgray = 2131034135;
			
			// aapt resource value: 0x7f050028
			public const int bottomactionbar_pressedcolor_black = 2131034152;
			
			// aapt resource value: 0x7f050030
			public const int bottomactionbar_pressedcolor_blue = 2131034160;
			
			// aapt resource value: 0x7f050020
			public const int bottomactionbar_pressedcolor_darkgray = 2131034144;
			
			// aapt resource value: 0x7f050018
			public const int bottomactionbar_pressedcolor_lightgray = 2131034136;
			
			// aapt resource value: 0x7f05000c
			public const int bottomactionbar_separator = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int bottomactionbar_title = 2131034125;
			
			// aapt resource value: 0x7f050034
			public const int green = 2131034164;
			
			// aapt resource value: 0x7f050037
			public const int grey = 2131034167;
			
			// aapt resource value: 0x7f050029
			public const int pager_black = 2131034153;
			
			// aapt resource value: 0x7f050031
			public const int pager_blue = 2131034161;
			
			// aapt resource value: 0x7f050021
			public const int pager_darkgray = 2131034145;
			
			// aapt resource value: 0x7f050019
			public const int pager_lightgray = 2131034137;
			
			// aapt resource value: 0x7f050035
			public const int red = 2131034165;
			
			// aapt resource value: 0x7f050032
			public const int white = 2131034162;
			
			// aapt resource value: 0x7f050038
			public const int yellow = 2131034168;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int actionbar_accentheight = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int actionbar_height = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int actionbar_home_item_width = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int actionbar_item_height = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int actionbar_item_height_over = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int actionbar_item_height_overflow = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int actionbar_item_width = 2131099652;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_back_indicator_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_background_alt = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_background_black = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int actionbar_background_blue = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int actionbar_background_darkgray = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int actionbar_background_lightgray = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int actionbar_btn = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int actionbar_btn_alt = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int actionbar_btn_black = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int actionbar_btn_blue = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int actionbar_btn_darkgray = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int actionbar_btn_lightgray = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int actionbar_btn_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int actionbar_btn_normal_alt = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int actionbar_btn_pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int actionbar_btn_pressed_alt = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bottomactionbar_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bottomactionbar_background_black = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bottomactionbar_background_blue = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bottomactionbar_background_darkgray = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bottomactionbar_background_lightgray = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bottomactionbar_btn = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bottomactionbar_btn_black = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bottomactionbar_btn_blue = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int bottomactionbar_btn_darkgray = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bottomactionbar_btn_lightgray = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bottomactionbar_btn_normal = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int bottomactionbar_btn_pressed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_action_down = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_action_down_dark = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_action_left = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_action_left_dark = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_action_overflow = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_action_overflow_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_action_refresh = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_action_refresh_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_action_right = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_action_right_dark = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_action_search = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_action_search_dark = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_action_share = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_action_share_dark = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_action_sort = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_action_sort_dark = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_action_up = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_action_up_dark = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_menu_down = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_menu_left = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_menu_refresh = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_menu_right = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_menu_search = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_menu_up = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int icon = 2130837558;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040010
			public const int actionbar = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public const int actionbar_actions = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int actionbar_home = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int actionbar_home_bg = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int actionbar_home_btn = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int actionbar_home_is_back = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int actionbar_home_logo = 2130968583;
			
			// aapt resource value: 0x7f04000f
			public const int actionbar_item = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int actionbar_progress = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int actionbar_title = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int actionbar_title_layout = 2130968588;
			
			// aapt resource value: 0x7f040016
			public const int add_action = 2130968598;
			
			// aapt resource value: 0x7f04001c
			public const int black_activity = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int blue_activity = 2130968605;
			
			// aapt resource value: 0x7f040011
			public const int bottomActionbar = 2130968593;
			
			// aapt resource value: 0x7f040000
			public const int custom = 2130968576;
			
			// aapt resource value: 0x7f04001e
			public const int fragment_activity = 2130968606;
			
			// aapt resource value: 0x7f040020
			public const int fragment_text = 2130968608;
			
			// aapt resource value: 0x7f04001a
			public const int gray_activity = 2130968602;
			
			// aapt resource value: 0x7f040003
			public const int holo_black = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int holo_blue = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int holo_gray = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int holo_light = 2130968577;
			
			// aapt resource value: 0x7f04001b
			public const int light_activity = 2130968603;
			
			// aapt resource value: 0x7f040024
			public const int menu_down = 2130968612;
			
			// aapt resource value: 0x7f040022
			public const int menu_left = 2130968610;
			
			// aapt resource value: 0x7f040026
			public const int menu_refresh = 2130968614;
			
			// aapt resource value: 0x7f040021
			public const int menu_right = 2130968609;
			
			// aapt resource value: 0x7f040025
			public const int menu_search = 2130968613;
			
			// aapt resource value: 0x7f040027
			public const int menu_test1 = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int menu_test2 = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int menu_test3 = 2130968617;
			
			// aapt resource value: 0x7f040023
			public const int menu_up = 2130968611;
			
			// aapt resource value: 0x7f040019
			public const int other_activity = 2130968601;
			
			// aapt resource value: 0x7f04001f
			public const int overflow_spinner = 2130968607;
			
			// aapt resource value: 0x7f040012
			public const int pager = 2130968594;
			
			// aapt resource value: 0x7f040017
			public const int remove_action = 2130968599;
			
			// aapt resource value: 0x7f040015
			public const int remove_actions = 2130968597;
			
			// aapt resource value: 0x7f040018
			public const int remove_share_action = 2130968600;
			
			// aapt resource value: 0x7f040005
			public const int screen = 2130968581;
			
			// aapt resource value: 0x7f040013
			public const int start_progress = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int stop_progress = 2130968596;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int black_theme = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int blankspinner = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int blue_theme = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_tabs = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int gray_theme = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int light_theme = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int other = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int overflowactionbar_item = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int simple_fragment = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int spinneritem = 2130903052;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int bottomactionbarmenus = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int mainmenu = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int othermainmenu = 2131296258;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int Hello = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int actionbar_activity_not_found = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int menu_string_down = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int menu_string_left = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int menu_string_refresh = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int menu_string_right = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int menu_string_search = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int menu_string_sort = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int menu_string_up = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int some_title = 2131165186;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080006
			public const int MyTheme = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int actionbar = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int actionbarhomeitem = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int actionbarhomelogo = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int actionbaritem = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int actionbarprogressbar = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int clearbutton = 2131230722;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] actionbar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 3
			public const int actionbar_background = 3;
			
			// aapt resource value: 4
			public const int actionbar_background_item = 4;
			
			// aapt resource value: 6
			public const int actionbar_is_bottom = 6;
			
			// aapt resource value: 7
			public const int actionbar_light_icons = 7;
			
			// aapt resource value: 2
			public const int actionbar_separator = 2;
			
			// aapt resource value: 5
			public const int actionbar_theme = 5;
			
			// aapt resource value: 0
			public const int actionbar_title = 0;
			
			// aapt resource value: 1
			public const int actionbar_title_color = 1;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
