#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LegacyBar.Sample.Resource", IsApplication=true)]

namespace LegacyBar.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LegacyBar.Library.Resource.Attribute.background = global::LegacyBar.Sample.Resource.Attribute.background;
			global::LegacyBar.Library.Resource.Attribute.background_item = global::LegacyBar.Sample.Resource.Attribute.background_item;
			global::LegacyBar.Library.Resource.Attribute.is_bottom = global::LegacyBar.Sample.Resource.Attribute.is_bottom;
			global::LegacyBar.Library.Resource.Attribute.light_icons = global::LegacyBar.Sample.Resource.Attribute.light_icons;
			global::LegacyBar.Library.Resource.Attribute.separator = global::LegacyBar.Sample.Resource.Attribute.separator;
			global::LegacyBar.Library.Resource.Attribute.theme = global::LegacyBar.Sample.Resource.Attribute.theme;
			global::LegacyBar.Library.Resource.Attribute.title = global::LegacyBar.Sample.Resource.Attribute.title;
			global::LegacyBar.Library.Resource.Attribute.title_color = global::LegacyBar.Sample.Resource.Attribute.title_color;
			global::LegacyBar.Library.Resource.Color.Red = global::LegacyBar.Sample.Resource.Color.Red;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_black = global::LegacyBar.Sample.Resource.Color.actionbar_accentcolor_black;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_blue = global::LegacyBar.Sample.Resource.Color.actionbar_accentcolor_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_darkgray = global::LegacyBar.Sample.Resource.Color.actionbar_accentcolor_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_accentcolor_lightgray = global::LegacyBar.Sample.Resource.Color.actionbar_accentcolor_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_background_end = global::LegacyBar.Sample.Resource.Color.actionbar_background_end;
			global::LegacyBar.Library.Resource.Color.actionbar_background_end_alt = global::LegacyBar.Sample.Resource.Color.actionbar_background_end_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end = global::LegacyBar.Sample.Resource.Color.actionbar_background_item_pressed_end;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end_alt = global::LegacyBar.Sample.Resource.Color.actionbar_background_item_pressed_end_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start = global::LegacyBar.Sample.Resource.Color.actionbar_background_item_pressed_start;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start_alt = global::LegacyBar.Sample.Resource.Color.actionbar_background_item_pressed_start_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_start = global::LegacyBar.Sample.Resource.Color.actionbar_background_start;
			global::LegacyBar.Library.Resource.Color.actionbar_background_start_alt = global::LegacyBar.Sample.Resource.Color.actionbar_background_start_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_black = global::LegacyBar.Sample.Resource.Color.actionbar_maincolor_black;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_blue = global::LegacyBar.Sample.Resource.Color.actionbar_maincolor_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_darkgray = global::LegacyBar.Sample.Resource.Color.actionbar_maincolor_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_maincolor_lightgray = global::LegacyBar.Sample.Resource.Color.actionbar_maincolor_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_black = global::LegacyBar.Sample.Resource.Color.actionbar_pressedcolor_black;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_blue = global::LegacyBar.Sample.Resource.Color.actionbar_pressedcolor_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_darkgray = global::LegacyBar.Sample.Resource.Color.actionbar_pressedcolor_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_pressedcolor_lightgray = global::LegacyBar.Sample.Resource.Color.actionbar_pressedcolor_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_separator = global::LegacyBar.Sample.Resource.Color.actionbar_separator;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_alt = global::LegacyBar.Sample.Resource.Color.actionbar_separator_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_black = global::LegacyBar.Sample.Resource.Color.actionbar_separator_black;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_blue = global::LegacyBar.Sample.Resource.Color.actionbar_separator_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_darkgray = global::LegacyBar.Sample.Resource.Color.actionbar_separator_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_lightgray = global::LegacyBar.Sample.Resource.Color.actionbar_separator_lightgray;
			global::LegacyBar.Library.Resource.Color.actionbar_title = global::LegacyBar.Sample.Resource.Color.actionbar_title;
			global::LegacyBar.Library.Resource.Color.actionbar_title_alt = global::LegacyBar.Sample.Resource.Color.actionbar_title_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_title_black = global::LegacyBar.Sample.Resource.Color.actionbar_title_black;
			global::LegacyBar.Library.Resource.Color.actionbar_title_blue = global::LegacyBar.Sample.Resource.Color.actionbar_title_blue;
			global::LegacyBar.Library.Resource.Color.actionbar_title_darkgray = global::LegacyBar.Sample.Resource.Color.actionbar_title_darkgray;
			global::LegacyBar.Library.Resource.Color.actionbar_title_lightgray = global::LegacyBar.Sample.Resource.Color.actionbar_title_lightgray;
			global::LegacyBar.Library.Resource.Color.black = global::LegacyBar.Sample.Resource.Color.black;
			global::LegacyBar.Library.Resource.Color.blue = global::LegacyBar.Sample.Resource.Color.blue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_end = global::LegacyBar.Sample.Resource.Color.bottomactionbar_background_end;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_end = global::LegacyBar.Sample.Resource.Color.bottomactionbar_background_item_pressed_end;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_start = global::LegacyBar.Sample.Resource.Color.bottomactionbar_background_item_pressed_start;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_start = global::LegacyBar.Sample.Resource.Color.bottomactionbar_background_start;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_black = global::LegacyBar.Sample.Resource.Color.bottomactionbar_maincolor_black;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_blue = global::LegacyBar.Sample.Resource.Color.bottomactionbar_maincolor_blue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_darkgray = global::LegacyBar.Sample.Resource.Color.bottomactionbar_maincolor_darkgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_maincolor_lightgray = global::LegacyBar.Sample.Resource.Color.bottomactionbar_maincolor_lightgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_black = global::LegacyBar.Sample.Resource.Color.bottomactionbar_pressedcolor_black;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_blue = global::LegacyBar.Sample.Resource.Color.bottomactionbar_pressedcolor_blue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_darkgray = global::LegacyBar.Sample.Resource.Color.bottomactionbar_pressedcolor_darkgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_pressedcolor_lightgray = global::LegacyBar.Sample.Resource.Color.bottomactionbar_pressedcolor_lightgray;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_separator = global::LegacyBar.Sample.Resource.Color.bottomactionbar_separator;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_title = global::LegacyBar.Sample.Resource.Color.bottomactionbar_title;
			global::LegacyBar.Library.Resource.Color.green = global::LegacyBar.Sample.Resource.Color.green;
			global::LegacyBar.Library.Resource.Color.grey = global::LegacyBar.Sample.Resource.Color.grey;
			global::LegacyBar.Library.Resource.Color.pager_black = global::LegacyBar.Sample.Resource.Color.pager_black;
			global::LegacyBar.Library.Resource.Color.pager_blue = global::LegacyBar.Sample.Resource.Color.pager_blue;
			global::LegacyBar.Library.Resource.Color.pager_darkgray = global::LegacyBar.Sample.Resource.Color.pager_darkgray;
			global::LegacyBar.Library.Resource.Color.pager_lightgray = global::LegacyBar.Sample.Resource.Color.pager_lightgray;
			global::LegacyBar.Library.Resource.Color.red = global::LegacyBar.Sample.Resource.Color.red;
			global::LegacyBar.Library.Resource.Color.white = global::LegacyBar.Sample.Resource.Color.white;
			global::LegacyBar.Library.Resource.Color.yellow = global::LegacyBar.Sample.Resource.Color.yellow;
			global::LegacyBar.Library.Resource.Dimension.actionbar_accentheight = global::LegacyBar.Sample.Resource.Dimension.actionbar_accentheight;
			global::LegacyBar.Library.Resource.Dimension.actionbar_height = global::LegacyBar.Sample.Resource.Dimension.actionbar_height;
			global::LegacyBar.Library.Resource.Dimension.actionbar_home_item_width = global::LegacyBar.Sample.Resource.Dimension.actionbar_home_item_width;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height = global::LegacyBar.Sample.Resource.Dimension.actionbar_item_height;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height_over = global::LegacyBar.Sample.Resource.Dimension.actionbar_item_height_over;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height_overflow = global::LegacyBar.Sample.Resource.Dimension.actionbar_item_height_overflow;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_width = global::LegacyBar.Sample.Resource.Dimension.actionbar_item_width;
			global::LegacyBar.Library.Resource.Drawable.actionbar_back_indicator = global::LegacyBar.Sample.Resource.Drawable.actionbar_back_indicator;
			global::LegacyBar.Library.Resource.Drawable.actionbar_back_indicator_dark = global::LegacyBar.Sample.Resource.Drawable.actionbar_back_indicator_dark;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background = global::LegacyBar.Sample.Resource.Drawable.actionbar_background;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_alt = global::LegacyBar.Sample.Resource.Drawable.actionbar_background_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_black = global::LegacyBar.Sample.Resource.Drawable.actionbar_background_black;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_blue = global::LegacyBar.Sample.Resource.Drawable.actionbar_background_blue;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_darkgray = global::LegacyBar.Sample.Resource.Drawable.actionbar_background_darkgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_lightgray = global::LegacyBar.Sample.Resource.Drawable.actionbar_background_lightgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn = global::LegacyBar.Sample.Resource.Drawable.actionbar_btn;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_alt = global::LegacyBar.Sample.Resource.Drawable.actionbar_btn_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_black = global::LegacyBar.Sample.Resource.Drawable.actionbar_btn_black;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_blue = global::LegacyBar.Sample.Resource.Drawable.actionbar_btn_blue;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_darkgray = global::LegacyBar.Sample.Resource.Drawable.actionbar_btn_darkgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_lightgray = global::LegacyBar.Sample.Resource.Drawable.actionbar_btn_lightgray;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_normal = global::LegacyBar.Sample.Resource.Drawable.actionbar_btn_normal;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_normal_alt = global::LegacyBar.Sample.Resource.Drawable.actionbar_btn_normal_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed = global::LegacyBar.Sample.Resource.Drawable.actionbar_btn_pressed;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed_alt = global::LegacyBar.Sample.Resource.Drawable.actionbar_btn_pressed_alt;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background = global::LegacyBar.Sample.Resource.Drawable.bottomactionbar_background;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_black = global::LegacyBar.Sample.Resource.Drawable.bottomactionbar_background_black;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_blue = global::LegacyBar.Sample.Resource.Drawable.bottomactionbar_background_blue;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_darkgray = global::LegacyBar.Sample.Resource.Drawable.bottomactionbar_background_darkgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background_lightgray = global::LegacyBar.Sample.Resource.Drawable.bottomactionbar_background_lightgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn = global::LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_black = global::LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn_black;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_blue = global::LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn_blue;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_darkgray = global::LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn_darkgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_lightgray = global::LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn_lightgray;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_normal = global::LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn_normal;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_pressed = global::LegacyBar.Sample.Resource.Drawable.bottomactionbar_btn_pressed;
			global::LegacyBar.Library.Resource.Drawable.dropdown_btn_holo_dark = global::LegacyBar.Sample.Resource.Drawable.dropdown_btn_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_btn_holo_light = global::LegacyBar.Sample.Resource.Drawable.dropdown_btn_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_disabled_holo_dark = global::LegacyBar.Sample.Resource.Drawable.dropdown_disabled_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_disabled_holo_light = global::LegacyBar.Sample.Resource.Drawable.dropdown_disabled_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_focused_holo_dark = global::LegacyBar.Sample.Resource.Drawable.dropdown_focused_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_focused_holo_light = global::LegacyBar.Sample.Resource.Drawable.dropdown_focused_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_normal_holo_dark = global::LegacyBar.Sample.Resource.Drawable.dropdown_normal_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_normal_holo_light = global::LegacyBar.Sample.Resource.Drawable.dropdown_normal_holo_light;
			global::LegacyBar.Library.Resource.Drawable.dropdown_pressed_holo_dark = global::LegacyBar.Sample.Resource.Drawable.dropdown_pressed_holo_dark;
			global::LegacyBar.Library.Resource.Drawable.dropdown_pressed_holo_light = global::LegacyBar.Sample.Resource.Drawable.dropdown_pressed_holo_light;
			global::LegacyBar.Library.Resource.Drawable.ic_action_overflow = global::LegacyBar.Sample.Resource.Drawable.ic_action_overflow;
			global::LegacyBar.Library.Resource.Drawable.ic_action_overflow_dark = global::LegacyBar.Sample.Resource.Drawable.ic_action_overflow_dark;
			global::LegacyBar.Library.Resource.Id.actionbar_actions = global::LegacyBar.Sample.Resource.Id.actionbar_actions;
			global::LegacyBar.Library.Resource.Id.actionbar_home = global::LegacyBar.Sample.Resource.Id.actionbar_home;
			global::LegacyBar.Library.Resource.Id.actionbar_home_bg = global::LegacyBar.Sample.Resource.Id.actionbar_home_bg;
			global::LegacyBar.Library.Resource.Id.actionbar_home_btn = global::LegacyBar.Sample.Resource.Id.actionbar_home_btn;
			global::LegacyBar.Library.Resource.Id.actionbar_home_is_back = global::LegacyBar.Sample.Resource.Id.actionbar_home_is_back;
			global::LegacyBar.Library.Resource.Id.actionbar_home_logo = global::LegacyBar.Sample.Resource.Id.actionbar_home_logo;
			global::LegacyBar.Library.Resource.Id.actionbar_item = global::LegacyBar.Sample.Resource.Id.actionbar_item;
			global::LegacyBar.Library.Resource.Id.actionbar_progress = global::LegacyBar.Sample.Resource.Id.actionbar_progress;
			global::LegacyBar.Library.Resource.Id.actionbar_spinner = global::LegacyBar.Sample.Resource.Id.actionbar_spinner;
			global::LegacyBar.Library.Resource.Id.actionbar_title = global::LegacyBar.Sample.Resource.Id.actionbar_title;
			global::LegacyBar.Library.Resource.Id.actionbar_title_layout = global::LegacyBar.Sample.Resource.Id.actionbar_title_layout;
			global::LegacyBar.Library.Resource.Id.custom = global::LegacyBar.Sample.Resource.Id.custom;
			global::LegacyBar.Library.Resource.Id.holo_black = global::LegacyBar.Sample.Resource.Id.holo_black;
			global::LegacyBar.Library.Resource.Id.holo_blue = global::LegacyBar.Sample.Resource.Id.holo_blue;
			global::LegacyBar.Library.Resource.Id.holo_gray = global::LegacyBar.Sample.Resource.Id.holo_gray;
			global::LegacyBar.Library.Resource.Id.holo_light = global::LegacyBar.Sample.Resource.Id.holo_light;
			global::LegacyBar.Library.Resource.Id.overflow_spinner = global::LegacyBar.Sample.Resource.Id.overflow_spinner;
			global::LegacyBar.Library.Resource.Id.screen = global::LegacyBar.Sample.Resource.Id.screen;
			global::LegacyBar.Library.Resource.Layout.actionbar = global::LegacyBar.Sample.Resource.Layout.actionbar;
			global::LegacyBar.Library.Resource.Layout.actionbar_item = global::LegacyBar.Sample.Resource.Layout.actionbar_item;
			global::LegacyBar.Library.Resource.Layout.blankspinner = global::LegacyBar.Sample.Resource.Layout.blankspinner;
			global::LegacyBar.Library.Resource.Layout.overflowactionbar_item = global::LegacyBar.Sample.Resource.Layout.overflowactionbar_item;
			global::LegacyBar.Library.Resource.Layout.spinneritem = global::LegacyBar.Sample.Resource.Layout.spinneritem;
			global::LegacyBar.Library.Resource.String.actionbar_activity_not_found = global::LegacyBar.Sample.Resource.String.actionbar_activity_not_found;
			global::LegacyBar.Library.Resource.Style.actionbar = global::LegacyBar.Sample.Resource.Style.actionbar;
			global::LegacyBar.Library.Resource.Style.actionbarhomeitem = global::LegacyBar.Sample.Resource.Style.actionbarhomeitem;
			global::LegacyBar.Library.Resource.Style.actionbarhomelogo = global::LegacyBar.Sample.Resource.Style.actionbarhomelogo;
			global::LegacyBar.Library.Resource.Style.actionbaritem = global::LegacyBar.Sample.Resource.Style.actionbaritem;
			global::LegacyBar.Library.Resource.Style.actionbarprogressbar = global::LegacyBar.Sample.Resource.Style.actionbarprogressbar;
			global::LegacyBar.Library.Resource.Style.clearbutton = global::LegacyBar.Sample.Resource.Style.clearbutton;
			global::LegacyBar.Library.Resource.Styleable.actionbar = global::LegacyBar.Sample.Resource.Styleable.actionbar;
			global::LegacyBar.Library.Resource.Styleable.actionbar_background = global::LegacyBar.Sample.Resource.Styleable.actionbar_background;
			global::LegacyBar.Library.Resource.Styleable.actionbar_background_item = global::LegacyBar.Sample.Resource.Styleable.actionbar_background_item;
			global::LegacyBar.Library.Resource.Styleable.actionbar_is_bottom = global::LegacyBar.Sample.Resource.Styleable.actionbar_is_bottom;
			global::LegacyBar.Library.Resource.Styleable.actionbar_light_icons = global::LegacyBar.Sample.Resource.Styleable.actionbar_light_icons;
			global::LegacyBar.Library.Resource.Styleable.actionbar_separator = global::LegacyBar.Sample.Resource.Styleable.actionbar_separator;
			global::LegacyBar.Library.Resource.Styleable.actionbar_theme = global::LegacyBar.Sample.Resource.Styleable.actionbar_theme;
			global::LegacyBar.Library.Resource.Styleable.actionbar_title = global::LegacyBar.Sample.Resource.Styleable.actionbar_title;
			global::LegacyBar.Library.Resource.Styleable.actionbar_title_color = global::LegacyBar.Sample.Resource.Styleable.actionbar_title_color;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int background = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int background_item = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int is_bottom = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int light_icons = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int separator = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int theme = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int title = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int title_color = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040039
			public const int Red = 2130968633;
			
			// aapt resource value: 0x7f040023
			public const int actionbar_accentcolor_black = 2130968611;
			
			// aapt resource value: 0x7f04002b
			public const int actionbar_accentcolor_blue = 2130968619;
			
			// aapt resource value: 0x7f04001b
			public const int actionbar_accentcolor_darkgray = 2130968603;
			
			// aapt resource value: 0x7f040013
			public const int actionbar_accentcolor_lightgray = 2130968595;
			
			// aapt resource value: 0x7f040003
			public const int actionbar_background_end = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int actionbar_background_end_alt = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int actionbar_background_item_pressed_end = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int actionbar_background_item_pressed_end_alt = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int actionbar_background_item_pressed_start = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int actionbar_background_item_pressed_start_alt = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int actionbar_background_start = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int actionbar_background_start_alt = 2130968584;
			
			// aapt resource value: 0x7f040022
			public const int actionbar_maincolor_black = 2130968610;
			
			// aapt resource value: 0x7f04002a
			public const int actionbar_maincolor_blue = 2130968618;
			
			// aapt resource value: 0x7f04001a
			public const int actionbar_maincolor_darkgray = 2130968602;
			
			// aapt resource value: 0x7f040012
			public const int actionbar_maincolor_lightgray = 2130968594;
			
			// aapt resource value: 0x7f040024
			public const int actionbar_pressedcolor_black = 2130968612;
			
			// aapt resource value: 0x7f04002c
			public const int actionbar_pressedcolor_blue = 2130968620;
			
			// aapt resource value: 0x7f04001c
			public const int actionbar_pressedcolor_darkgray = 2130968604;
			
			// aapt resource value: 0x7f040014
			public const int actionbar_pressedcolor_lightgray = 2130968596;
			
			// aapt resource value: 0x7f040000
			public const int actionbar_separator = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int actionbar_separator_alt = 2130968582;
			
			// aapt resource value: 0x7f040026
			public const int actionbar_separator_black = 2130968614;
			
			// aapt resource value: 0x7f04002e
			public const int actionbar_separator_blue = 2130968622;
			
			// aapt resource value: 0x7f04001e
			public const int actionbar_separator_darkgray = 2130968606;
			
			// aapt resource value: 0x7f040016
			public const int actionbar_separator_lightgray = 2130968598;
			
			// aapt resource value: 0x7f040001
			public const int actionbar_title = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int actionbar_title_alt = 2130968583;
			
			// aapt resource value: 0x7f040025
			public const int actionbar_title_black = 2130968613;
			
			// aapt resource value: 0x7f04002d
			public const int actionbar_title_blue = 2130968621;
			
			// aapt resource value: 0x7f04001d
			public const int actionbar_title_darkgray = 2130968605;
			
			// aapt resource value: 0x7f040015
			public const int actionbar_title_lightgray = 2130968597;
			
			// aapt resource value: 0x7f040033
			public const int black = 2130968627;
			
			// aapt resource value: 0x7f040036
			public const int blue = 2130968630;
			
			// aapt resource value: 0x7f04000f
			public const int bottomactionbar_background_end = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int bottomactionbar_background_item_pressed_end = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int bottomactionbar_background_item_pressed_start = 2130968593;
			
			// aapt resource value: 0x7f04000e
			public const int bottomactionbar_background_start = 2130968590;
			
			// aapt resource value: 0x7f040027
			public const int bottomactionbar_maincolor_black = 2130968615;
			
			// aapt resource value: 0x7f04002f
			public const int bottomactionbar_maincolor_blue = 2130968623;
			
			// aapt resource value: 0x7f04001f
			public const int bottomactionbar_maincolor_darkgray = 2130968607;
			
			// aapt resource value: 0x7f040017
			public const int bottomactionbar_maincolor_lightgray = 2130968599;
			
			// aapt resource value: 0x7f040028
			public const int bottomactionbar_pressedcolor_black = 2130968616;
			
			// aapt resource value: 0x7f040030
			public const int bottomactionbar_pressedcolor_blue = 2130968624;
			
			// aapt resource value: 0x7f040020
			public const int bottomactionbar_pressedcolor_darkgray = 2130968608;
			
			// aapt resource value: 0x7f040018
			public const int bottomactionbar_pressedcolor_lightgray = 2130968600;
			
			// aapt resource value: 0x7f04000c
			public const int bottomactionbar_separator = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int bottomactionbar_title = 2130968589;
			
			// aapt resource value: 0x7f040034
			public const int green = 2130968628;
			
			// aapt resource value: 0x7f040037
			public const int grey = 2130968631;
			
			// aapt resource value: 0x7f040029
			public const int pager_black = 2130968617;
			
			// aapt resource value: 0x7f040031
			public const int pager_blue = 2130968625;
			
			// aapt resource value: 0x7f040021
			public const int pager_darkgray = 2130968609;
			
			// aapt resource value: 0x7f040019
			public const int pager_lightgray = 2130968601;
			
			// aapt resource value: 0x7f040035
			public const int red = 2130968629;
			
			// aapt resource value: 0x7f040032
			public const int white = 2130968626;
			
			// aapt resource value: 0x7f040038
			public const int yellow = 2130968632;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int actionbar_accentheight = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int actionbar_height = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int actionbar_home_item_width = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int actionbar_item_height = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int actionbar_item_height_over = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int actionbar_item_height_overflow = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int actionbar_item_width = 2131034116;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_back_indicator_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_background_alt = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_background_black = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int actionbar_background_blue = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int actionbar_background_darkgray = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int actionbar_background_lightgray = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int actionbar_btn = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int actionbar_btn_alt = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int actionbar_btn_black = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int actionbar_btn_blue = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int actionbar_btn_darkgray = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int actionbar_btn_lightgray = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int actionbar_btn_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int actionbar_btn_normal_alt = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int actionbar_btn_pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int actionbar_btn_pressed_alt = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bottomactionbar_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bottomactionbar_background_black = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bottomactionbar_background_blue = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bottomactionbar_background_darkgray = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bottomactionbar_background_lightgray = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bottomactionbar_btn = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bottomactionbar_btn_black = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bottomactionbar_btn_blue = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int bottomactionbar_btn_darkgray = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bottomactionbar_btn_lightgray = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bottomactionbar_btn_normal = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int bottomactionbar_btn_pressed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int dropdown_btn_holo_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int dropdown_btn_holo_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int dropdown_disabled_holo_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int dropdown_disabled_holo_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int dropdown_focused_holo_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int dropdown_focused_holo_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int dropdown_normal_holo_dark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int dropdown_normal_holo_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int dropdown_pressed_holo_dark = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int dropdown_pressed_holo_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_action_down = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_action_down_dark = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_action_left = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_action_left_dark = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_action_overflow = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_action_overflow_dark = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_action_refresh = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_action_refresh_dark = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_action_right = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_action_right_dark = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_action_search = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_action_search_dark = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_action_share = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_action_share_dark = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_action_sort = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_action_sort_dark = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_action_up = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_action_up_dark = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_menu_down = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic_menu_left = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_menu_refresh = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_menu_right = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_menu_search = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_menu_up = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int icon = 2130837568;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090011
			public const int actionbar = 2131296273;
			
			// aapt resource value: 0x7f09000b
			public const int actionbar_actions = 2131296267;
			
			// aapt resource value: 0x7f090006
			public const int actionbar_home = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int actionbar_home_bg = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int actionbar_home_btn = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int actionbar_home_is_back = 2131296266;
			
			// aapt resource value: 0x7f090007
			public const int actionbar_home_logo = 2131296263;
			
			// aapt resource value: 0x7f090010
			public const int actionbar_item = 2131296272;
			
			// aapt resource value: 0x7f09000d
			public const int actionbar_progress = 2131296269;
			
			// aapt resource value: 0x7f09000f
			public const int actionbar_spinner = 2131296271;
			
			// aapt resource value: 0x7f09000e
			public const int actionbar_title = 2131296270;
			
			// aapt resource value: 0x7f09000c
			public const int actionbar_title_layout = 2131296268;
			
			// aapt resource value: 0x7f090017
			public const int add_action = 2131296279;
			
			// aapt resource value: 0x7f09001d
			public const int black_activity = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int blue_activity = 2131296286;
			
			// aapt resource value: 0x7f090012
			public const int bottomActionbar = 2131296274;
			
			// aapt resource value: 0x7f090000
			public const int custom = 2131296256;
			
			// aapt resource value: 0x7f09001f
			public const int dropdown_activity = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int fragment_activity = 2131296288;
			
			// aapt resource value: 0x7f090022
			public const int fragment_text = 2131296290;
			
			// aapt resource value: 0x7f09001b
			public const int gray_activity = 2131296283;
			
			// aapt resource value: 0x7f090001
			public const int holo_black = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int holo_blue = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int holo_gray = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int holo_light = 2131296260;
			
			// aapt resource value: 0x7f09001c
			public const int light_activity = 2131296284;
			
			// aapt resource value: 0x7f090026
			public const int menu_down = 2131296294;
			
			// aapt resource value: 0x7f090024
			public const int menu_left = 2131296292;
			
			// aapt resource value: 0x7f090028
			public const int menu_refresh = 2131296296;
			
			// aapt resource value: 0x7f090023
			public const int menu_right = 2131296291;
			
			// aapt resource value: 0x7f090027
			public const int menu_search = 2131296295;
			
			// aapt resource value: 0x7f090029
			public const int menu_test1 = 2131296297;
			
			// aapt resource value: 0x7f09002a
			public const int menu_test2 = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int menu_test3 = 2131296299;
			
			// aapt resource value: 0x7f090025
			public const int menu_up = 2131296293;
			
			// aapt resource value: 0x7f09001a
			public const int other_activity = 2131296282;
			
			// aapt resource value: 0x7f090021
			public const int overflow_spinner = 2131296289;
			
			// aapt resource value: 0x7f090013
			public const int pager = 2131296275;
			
			// aapt resource value: 0x7f090018
			public const int remove_action = 2131296280;
			
			// aapt resource value: 0x7f090016
			public const int remove_actions = 2131296278;
			
			// aapt resource value: 0x7f090019
			public const int remove_share_action = 2131296281;
			
			// aapt resource value: 0x7f090005
			public const int screen = 2131296261;
			
			// aapt resource value: 0x7f090014
			public const int start_progress = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int stop_progress = 2131296277;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int black_theme = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int blankspinner = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int blue_theme = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_tabs = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int gray_theme = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int light_theme = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int other = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int overflowactionbar_item = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int simple_fragment = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int spinneritem = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int bottomactionbarmenus = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int mainmenu = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int othermainmenu = 2131230722;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int Hello = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int actionbar_activity_not_found = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int menu_string_down = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int menu_string_left = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int menu_string_refresh = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int menu_string_right = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int menu_string_search = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int menu_string_sort = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int menu_string_up = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int some_title = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070006
			public const int MyTheme = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int actionbar = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int actionbarhomeitem = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int actionbarhomelogo = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int actionbaritem = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int actionbarprogressbar = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int clearbutton = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] actionbar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 3
			public const int actionbar_background = 3;
			
			// aapt resource value: 4
			public const int actionbar_background_item = 4;
			
			// aapt resource value: 6
			public const int actionbar_is_bottom = 6;
			
			// aapt resource value: 7
			public const int actionbar_light_icons = 7;
			
			// aapt resource value: 2
			public const int actionbar_separator = 2;
			
			// aapt resource value: 5
			public const int actionbar_theme = 5;
			
			// aapt resource value: 0
			public const int actionbar_title = 0;
			
			// aapt resource value: 1
			public const int actionbar_title_color = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
