//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoDroid.ActionBarSample
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int title = 2130771968;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int actionbar_background_end = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int actionbar_background_item_pressed_end = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int actionbar_background_item_pressed_start = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int actionbar_background_start = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int actionbar_separator = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int actionbar_title = 2130968577;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int actionbar_height = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int actionbar_item_height = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int actionbar_item_width = 2131034114;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_btn = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_btn_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_btn_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_refresh_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_search_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_refresh = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_search = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_title_export_default = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_title_home_default = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_title_home_demo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_title_share_default = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000a
			public const int actionbar = 2131296266;
			
			// aapt resource value: 0x7f090006
			public const int actionbar_actions = 2131296262;
			
			// aapt resource value: 0x7f090001
			public const int actionbar_home = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int actionbar_home_bg = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int actionbar_home_btn = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int actionbar_home_is_back = 2131296261;
			
			// aapt resource value: 0x7f090002
			public const int actionbar_home_logo = 2131296258;
			
			// aapt resource value: 0x7f090009
			public const int actionbar_item = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int actionbar_progress = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int actionbar_title = 2131296264;
			
			// aapt resource value: 0x7f09000e
			public const int add_action = 2131296270;
			
			// aapt resource value: 0x7f090012
			public const int menu_refresh = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int menu_search = 2131296273;
			
			// aapt resource value: 0x7f09000f
			public const int remove_action = 2131296271;
			
			// aapt resource value: 0x7f09000d
			public const int remove_actions = 2131296269;
			
			// aapt resource value: 0x7f090010
			public const int remove_share_action = 2131296272;
			
			// aapt resource value: 0x7f090000
			public const int screen = 2131296256;
			
			// aapt resource value: 0x7f09000b
			public const int start_progress = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int stop_progress = 2131296268;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActionBar_Item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Other = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int MainMenu = 2131230720;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int actionbar_activity_not_found = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int some_title = 2131099651;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int ActionBar = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int ActionBarHomeItem = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int ActionBarHomeLogo = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int ActionBarItem = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int ActionBarProgressBar = 2131165188;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionBar = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int ActionBar_title = 0;
			
			private Styleable()
			{
			}
		}
	}
}
