#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MonoDroid.ActionBar.Library.Resource", IsApplication=false)]

namespace MonoDroid.ActionBar.Library
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int background = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int background_item = 2130771972;
			
			// aapt resource value: 0x7f010002
			public static int separator = 2130771970;
			
			// aapt resource value: 0x7f010000
			public static int title = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int title_color = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040019
			public static int Red = 2130968601;
			
			// aapt resource value: 0x7f040003
			public static int actionbar_background_end = 2130968579;
			
			// aapt resource value: 0x7f040009
			public static int actionbar_background_end_alt = 2130968585;
			
			// aapt resource value: 0x7f040005
			public static int actionbar_background_item_pressed_end = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public static int actionbar_background_item_pressed_end_alt = 2130968587;
			
			// aapt resource value: 0x7f040004
			public static int actionbar_background_item_pressed_start = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public static int actionbar_background_item_pressed_start_alt = 2130968586;
			
			// aapt resource value: 0x7f040002
			public static int actionbar_background_start = 2130968578;
			
			// aapt resource value: 0x7f040008
			public static int actionbar_background_start_alt = 2130968584;
			
			// aapt resource value: 0x7f040000
			public static int actionbar_separator = 2130968576;
			
			// aapt resource value: 0x7f040006
			public static int actionbar_separator_alt = 2130968582;
			
			// aapt resource value: 0x7f040001
			public static int actionbar_title = 2130968577;
			
			// aapt resource value: 0x7f040007
			public static int actionbar_title_alt = 2130968583;
			
			// aapt resource value: 0x7f040013
			public static int black = 2130968595;
			
			// aapt resource value: 0x7f040016
			public static int blue = 2130968598;
			
			// aapt resource value: 0x7f04000f
			public static int bottomactionbar_background_end = 2130968591;
			
			// aapt resource value: 0x7f040010
			public static int bottomactionbar_background_item_pressed_end = 2130968592;
			
			// aapt resource value: 0x7f040011
			public static int bottomactionbar_background_item_pressed_start = 2130968593;
			
			// aapt resource value: 0x7f04000e
			public static int bottomactionbar_background_start = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public static int bottomactionbar_separator = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public static int bottomactionbar_title = 2130968589;
			
			// aapt resource value: 0x7f040014
			public static int green = 2130968596;
			
			// aapt resource value: 0x7f040017
			public static int grey = 2130968599;
			
			// aapt resource value: 0x7f040015
			public static int red = 2130968597;
			
			// aapt resource value: 0x7f040012
			public static int white = 2130968594;
			
			// aapt resource value: 0x7f040018
			public static int yellow = 2130968600;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public static int actionbar_height = 2131034112;
			
			// aapt resource value: 0x7f050004
			public static int actionbar_home_item_width = 2131034116;
			
			// aapt resource value: 0x7f050001
			public static int actionbar_item_height = 2131034113;
			
			// aapt resource value: 0x7f050005
			public static int actionbar_item_height_over = 2131034117;
			
			// aapt resource value: 0x7f050002
			public static int actionbar_item_height_overflow = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int actionbar_item_width = 2131034115;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int actionbar_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int actionbar_background_alt = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int actionbar_btn = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int actionbar_btn_alt = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int actionbar_btn_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int actionbar_btn_normal_alt = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int actionbar_btn_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int actionbar_btn_pressed_alt = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int bottomactionbar_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int bottomactionbar_btn = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int bottomactionbar_btn_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int bottomactionbar_btn_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int ic_action_down = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int ic_action_left = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int ic_action_overflow_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int ic_action_refresh_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int ic_action_right = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int ic_action_search_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int ic_action_up = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int ic_launcher = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int ic_menu_down = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int ic_menu_left = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int ic_menu_refresh = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int ic_menu_right = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int ic_menu_search = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int ic_menu_up = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int ic_title_export_default = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int ic_title_share_default = 2130837532;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public static int actionbar_actions = 2131230726;
			
			// aapt resource value: 0x7f080001
			public static int actionbar_home = 2131230721;
			
			// aapt resource value: 0x7f080003
			public static int actionbar_home_bg = 2131230723;
			
			// aapt resource value: 0x7f080004
			public static int actionbar_home_btn = 2131230724;
			
			// aapt resource value: 0x7f080005
			public static int actionbar_home_is_back = 2131230725;
			
			// aapt resource value: 0x7f080002
			public static int actionbar_home_logo = 2131230722;
			
			// aapt resource value: 0x7f08000a
			public static int actionbar_item = 2131230730;
			
			// aapt resource value: 0x7f080008
			public static int actionbar_progress = 2131230728;
			
			// aapt resource value: 0x7f080009
			public static int actionbar_title = 2131230729;
			
			// aapt resource value: 0x7f080007
			public static int actionbar_title_layout = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public static int overflow_spinner = 2131230731;
			
			// aapt resource value: 0x7f080000
			public static int screen = 2131230720;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int actionbar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int actionbar_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int blankspinner = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int overflowactionbar_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int spinneritem = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public static int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public static int actionbar_activity_not_found = 2131099650;
			
			// aapt resource value: 0x7f060001
			public static int app_name = 2131099649;
			
			// aapt resource value: 0x7f060006
			public static int menu_string_down = 2131099654;
			
			// aapt resource value: 0x7f060007
			public static int menu_string_left = 2131099655;
			
			// aapt resource value: 0x7f060009
			public static int menu_string_refresh = 2131099657;
			
			// aapt resource value: 0x7f060008
			public static int menu_string_right = 2131099656;
			
			// aapt resource value: 0x7f060004
			public static int menu_string_search = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int menu_string_up = 2131099653;
			
			// aapt resource value: 0x7f060003
			public static int some_title = 2131099651;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070006
			public static int MyTheme = 2131165190;
			
			// aapt resource value: 0x7f070000
			public static int actionbar = 2131165184;
			
			// aapt resource value: 0x7f070003
			public static int actionbarhomeitem = 2131165187;
			
			// aapt resource value: 0x7f070004
			public static int actionbarhomelogo = 2131165188;
			
			// aapt resource value: 0x7f070001
			public static int actionbaritem = 2131165185;
			
			// aapt resource value: 0x7f070005
			public static int actionbarprogressbar = 2131165189;
			
			// aapt resource value: 0x7f070002
			public static int clearbutton = 2131165186;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] actionbar = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 3
			public static int actionbar_background = 3;
			
			// aapt resource value: 4
			public static int actionbar_background_item = 4;
			
			// aapt resource value: 2
			public static int actionbar_separator = 2;
			
			// aapt resource value: 0
			public static int actionbar_title = 0;
			
			// aapt resource value: 1
			public static int actionbar_title_color = 1;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
