#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LegacyBar.Library.Resource", IsApplication=false)]

namespace LegacyBar.Library
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int background = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int background_item = 2130771972;
			
			// aapt resource value: 0x7f010006
			public static int is_bottom = 2130771974;
			
			// aapt resource value: 0x7f010007
			public static int light_icons = 2130771975;
			
			// aapt resource value: 0x7f010002
			public static int separator = 2130771970;
			
			// aapt resource value: 0x7f010005
			public static int theme = 2130771973;
			
			// aapt resource value: 0x7f010000
			public static int title = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int title_color = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040039
			public static int Red = 2130968633;
			
			// aapt resource value: 0x7f040023
			public static int actionbar_accentcolor_black = 2130968611;
			
			// aapt resource value: 0x7f04002b
			public static int actionbar_accentcolor_blue = 2130968619;
			
			// aapt resource value: 0x7f04001b
			public static int actionbar_accentcolor_darkgray = 2130968603;
			
			// aapt resource value: 0x7f040013
			public static int actionbar_accentcolor_lightgray = 2130968595;
			
			// aapt resource value: 0x7f040003
			public static int actionbar_background_end = 2130968579;
			
			// aapt resource value: 0x7f040009
			public static int actionbar_background_end_alt = 2130968585;
			
			// aapt resource value: 0x7f040005
			public static int actionbar_background_item_pressed_end = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public static int actionbar_background_item_pressed_end_alt = 2130968587;
			
			// aapt resource value: 0x7f040004
			public static int actionbar_background_item_pressed_start = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public static int actionbar_background_item_pressed_start_alt = 2130968586;
			
			// aapt resource value: 0x7f040002
			public static int actionbar_background_start = 2130968578;
			
			// aapt resource value: 0x7f040008
			public static int actionbar_background_start_alt = 2130968584;
			
			// aapt resource value: 0x7f040022
			public static int actionbar_maincolor_black = 2130968610;
			
			// aapt resource value: 0x7f04002a
			public static int actionbar_maincolor_blue = 2130968618;
			
			// aapt resource value: 0x7f04001a
			public static int actionbar_maincolor_darkgray = 2130968602;
			
			// aapt resource value: 0x7f040012
			public static int actionbar_maincolor_lightgray = 2130968594;
			
			// aapt resource value: 0x7f040024
			public static int actionbar_pressedcolor_black = 2130968612;
			
			// aapt resource value: 0x7f04002c
			public static int actionbar_pressedcolor_blue = 2130968620;
			
			// aapt resource value: 0x7f04001c
			public static int actionbar_pressedcolor_darkgray = 2130968604;
			
			// aapt resource value: 0x7f040014
			public static int actionbar_pressedcolor_lightgray = 2130968596;
			
			// aapt resource value: 0x7f040000
			public static int actionbar_separator = 2130968576;
			
			// aapt resource value: 0x7f040006
			public static int actionbar_separator_alt = 2130968582;
			
			// aapt resource value: 0x7f040026
			public static int actionbar_separator_black = 2130968614;
			
			// aapt resource value: 0x7f04002e
			public static int actionbar_separator_blue = 2130968622;
			
			// aapt resource value: 0x7f04001e
			public static int actionbar_separator_darkgray = 2130968606;
			
			// aapt resource value: 0x7f040016
			public static int actionbar_separator_lightgray = 2130968598;
			
			// aapt resource value: 0x7f040001
			public static int actionbar_title = 2130968577;
			
			// aapt resource value: 0x7f040007
			public static int actionbar_title_alt = 2130968583;
			
			// aapt resource value: 0x7f040025
			public static int actionbar_title_black = 2130968613;
			
			// aapt resource value: 0x7f04002d
			public static int actionbar_title_blue = 2130968621;
			
			// aapt resource value: 0x7f04001d
			public static int actionbar_title_darkgray = 2130968605;
			
			// aapt resource value: 0x7f040015
			public static int actionbar_title_lightgray = 2130968597;
			
			// aapt resource value: 0x7f040033
			public static int black = 2130968627;
			
			// aapt resource value: 0x7f040036
			public static int blue = 2130968630;
			
			// aapt resource value: 0x7f04000f
			public static int bottomactionbar_background_end = 2130968591;
			
			// aapt resource value: 0x7f040010
			public static int bottomactionbar_background_item_pressed_end = 2130968592;
			
			// aapt resource value: 0x7f040011
			public static int bottomactionbar_background_item_pressed_start = 2130968593;
			
			// aapt resource value: 0x7f04000e
			public static int bottomactionbar_background_start = 2130968590;
			
			// aapt resource value: 0x7f040027
			public static int bottomactionbar_maincolor_black = 2130968615;
			
			// aapt resource value: 0x7f04002f
			public static int bottomactionbar_maincolor_blue = 2130968623;
			
			// aapt resource value: 0x7f04001f
			public static int bottomactionbar_maincolor_darkgray = 2130968607;
			
			// aapt resource value: 0x7f040017
			public static int bottomactionbar_maincolor_lightgray = 2130968599;
			
			// aapt resource value: 0x7f040028
			public static int bottomactionbar_pressedcolor_black = 2130968616;
			
			// aapt resource value: 0x7f040030
			public static int bottomactionbar_pressedcolor_blue = 2130968624;
			
			// aapt resource value: 0x7f040020
			public static int bottomactionbar_pressedcolor_darkgray = 2130968608;
			
			// aapt resource value: 0x7f040018
			public static int bottomactionbar_pressedcolor_lightgray = 2130968600;
			
			// aapt resource value: 0x7f04000c
			public static int bottomactionbar_separator = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public static int bottomactionbar_title = 2130968589;
			
			// aapt resource value: 0x7f040034
			public static int green = 2130968628;
			
			// aapt resource value: 0x7f040037
			public static int grey = 2130968631;
			
			// aapt resource value: 0x7f040029
			public static int pager_black = 2130968617;
			
			// aapt resource value: 0x7f040031
			public static int pager_blue = 2130968625;
			
			// aapt resource value: 0x7f040021
			public static int pager_darkgray = 2130968609;
			
			// aapt resource value: 0x7f040019
			public static int pager_lightgray = 2130968601;
			
			// aapt resource value: 0x7f040035
			public static int red = 2130968629;
			
			// aapt resource value: 0x7f040032
			public static int white = 2130968626;
			
			// aapt resource value: 0x7f040038
			public static int yellow = 2130968632;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public static int actionbar_accentheight = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int actionbar_height = 2131034113;
			
			// aapt resource value: 0x7f050005
			public static int actionbar_home_item_width = 2131034117;
			
			// aapt resource value: 0x7f050002
			public static int actionbar_item_height = 2131034114;
			
			// aapt resource value: 0x7f050006
			public static int actionbar_item_height_over = 2131034118;
			
			// aapt resource value: 0x7f050003
			public static int actionbar_item_height_overflow = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int actionbar_item_width = 2131034116;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int actionbar_back_indicator_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int actionbar_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int actionbar_background_alt = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int actionbar_background_black = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int actionbar_background_blue = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int actionbar_background_darkgray = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int actionbar_background_lightgray = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int actionbar_btn = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int actionbar_btn_alt = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int actionbar_btn_black = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int actionbar_btn_blue = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int actionbar_btn_darkgray = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int actionbar_btn_lightgray = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int actionbar_btn_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int actionbar_btn_normal_alt = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int actionbar_btn_pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int actionbar_btn_pressed_alt = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int bottomactionbar_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int bottomactionbar_background_black = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int bottomactionbar_background_blue = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int bottomactionbar_background_darkgray = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int bottomactionbar_background_lightgray = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int bottomactionbar_btn = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int bottomactionbar_btn_black = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int bottomactionbar_btn_blue = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int bottomactionbar_btn_darkgray = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int bottomactionbar_btn_lightgray = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int bottomactionbar_btn_normal = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public static int bottomactionbar_btn_pressed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int dropdown_btn_holo_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int dropdown_btn_holo_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public static int dropdown_disabled_holo_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public static int dropdown_disabled_holo_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public static int dropdown_focused_holo_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public static int dropdown_focused_holo_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public static int dropdown_normal_holo_dark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public static int dropdown_normal_holo_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public static int dropdown_pressed_holo_dark = 2130837542;
			
			// aapt resource value: 0x7f020027
			public static int dropdown_pressed_holo_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public static int ic_action_overflow = 2130837544;
			
			// aapt resource value: 0x7f020029
			public static int ic_action_overflow_dark = 2130837545;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public static int actionbar_actions = 2131230731;
			
			// aapt resource value: 0x7f080006
			public static int actionbar_home = 2131230726;
			
			// aapt resource value: 0x7f080008
			public static int actionbar_home_bg = 2131230728;
			
			// aapt resource value: 0x7f080009
			public static int actionbar_home_btn = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public static int actionbar_home_is_back = 2131230730;
			
			// aapt resource value: 0x7f080007
			public static int actionbar_home_logo = 2131230727;
			
			// aapt resource value: 0x7f080010
			public static int actionbar_item = 2131230736;
			
			// aapt resource value: 0x7f08000d
			public static int actionbar_progress = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public static int actionbar_spinner = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public static int actionbar_title = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public static int actionbar_title_layout = 2131230732;
			
			// aapt resource value: 0x7f080000
			public static int custom = 2131230720;
			
			// aapt resource value: 0x7f080001
			public static int holo_black = 2131230721;
			
			// aapt resource value: 0x7f080002
			public static int holo_blue = 2131230722;
			
			// aapt resource value: 0x7f080003
			public static int holo_gray = 2131230723;
			
			// aapt resource value: 0x7f080004
			public static int holo_light = 2131230724;
			
			// aapt resource value: 0x7f080011
			public static int overflow_spinner = 2131230737;
			
			// aapt resource value: 0x7f080005
			public static int screen = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int actionbar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int actionbar_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int blankspinner = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int overflowactionbar_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int spinneritem = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public static int actionbar_activity_not_found = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public static int actionbar = 2131165184;
			
			// aapt resource value: 0x7f070003
			public static int actionbarhomeitem = 2131165187;
			
			// aapt resource value: 0x7f070004
			public static int actionbarhomelogo = 2131165188;
			
			// aapt resource value: 0x7f070001
			public static int actionbaritem = 2131165185;
			
			// aapt resource value: 0x7f070005
			public static int actionbarprogressbar = 2131165189;
			
			// aapt resource value: 0x7f070002
			public static int clearbutton = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] actionbar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 3
			public static int actionbar_background = 3;
			
			// aapt resource value: 4
			public static int actionbar_background_item = 4;
			
			// aapt resource value: 6
			public static int actionbar_is_bottom = 6;
			
			// aapt resource value: 7
			public static int actionbar_light_icons = 7;
			
			// aapt resource value: 2
			public static int actionbar_separator = 2;
			
			// aapt resource value: 5
			public static int actionbar_theme = 5;
			
			// aapt resource value: 0
			public static int actionbar_title = 0;
			
			// aapt resource value: 1
			public static int actionbar_title_color = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
