#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("LegacyBar.Library.Resource", IsApplication=false)]

namespace LegacyBar.Library
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int background = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int background_item = 2130771972;
			
			// aapt resource value: 0x7f010006
			public static int is_bottom = 2130771974;
			
			// aapt resource value: 0x7f010007
			public static int light_icons = 2130771975;
			
			// aapt resource value: 0x7f010002
			public static int separator = 2130771970;
			
			// aapt resource value: 0x7f010005
			public static int theme = 2130771973;
			
			// aapt resource value: 0x7f010000
			public static int title = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int title_color = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050039
			public static int Red = 2131034169;
			
			// aapt resource value: 0x7f050023
			public static int actionbar_accentcolor_black = 2131034147;
			
			// aapt resource value: 0x7f05002b
			public static int actionbar_accentcolor_blue = 2131034155;
			
			// aapt resource value: 0x7f05001b
			public static int actionbar_accentcolor_darkgray = 2131034139;
			
			// aapt resource value: 0x7f050013
			public static int actionbar_accentcolor_lightgray = 2131034131;
			
			// aapt resource value: 0x7f050003
			public static int actionbar_background_end = 2131034115;
			
			// aapt resource value: 0x7f050009
			public static int actionbar_background_end_alt = 2131034121;
			
			// aapt resource value: 0x7f050005
			public static int actionbar_background_item_pressed_end = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public static int actionbar_background_item_pressed_end_alt = 2131034123;
			
			// aapt resource value: 0x7f050004
			public static int actionbar_background_item_pressed_start = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public static int actionbar_background_item_pressed_start_alt = 2131034122;
			
			// aapt resource value: 0x7f050002
			public static int actionbar_background_start = 2131034114;
			
			// aapt resource value: 0x7f050008
			public static int actionbar_background_start_alt = 2131034120;
			
			// aapt resource value: 0x7f050022
			public static int actionbar_maincolor_black = 2131034146;
			
			// aapt resource value: 0x7f05002a
			public static int actionbar_maincolor_blue = 2131034154;
			
			// aapt resource value: 0x7f05001a
			public static int actionbar_maincolor_darkgray = 2131034138;
			
			// aapt resource value: 0x7f050012
			public static int actionbar_maincolor_lightgray = 2131034130;
			
			// aapt resource value: 0x7f050024
			public static int actionbar_pressedcolor_black = 2131034148;
			
			// aapt resource value: 0x7f05002c
			public static int actionbar_pressedcolor_blue = 2131034156;
			
			// aapt resource value: 0x7f05001c
			public static int actionbar_pressedcolor_darkgray = 2131034140;
			
			// aapt resource value: 0x7f050014
			public static int actionbar_pressedcolor_lightgray = 2131034132;
			
			// aapt resource value: 0x7f050000
			public static int actionbar_separator = 2131034112;
			
			// aapt resource value: 0x7f050006
			public static int actionbar_separator_alt = 2131034118;
			
			// aapt resource value: 0x7f050026
			public static int actionbar_separator_black = 2131034150;
			
			// aapt resource value: 0x7f05002e
			public static int actionbar_separator_blue = 2131034158;
			
			// aapt resource value: 0x7f05001e
			public static int actionbar_separator_darkgray = 2131034142;
			
			// aapt resource value: 0x7f050016
			public static int actionbar_separator_lightgray = 2131034134;
			
			// aapt resource value: 0x7f050001
			public static int actionbar_title = 2131034113;
			
			// aapt resource value: 0x7f050007
			public static int actionbar_title_alt = 2131034119;
			
			// aapt resource value: 0x7f050025
			public static int actionbar_title_black = 2131034149;
			
			// aapt resource value: 0x7f05002d
			public static int actionbar_title_blue = 2131034157;
			
			// aapt resource value: 0x7f05001d
			public static int actionbar_title_darkgray = 2131034141;
			
			// aapt resource value: 0x7f050015
			public static int actionbar_title_lightgray = 2131034133;
			
			// aapt resource value: 0x7f050033
			public static int black = 2131034163;
			
			// aapt resource value: 0x7f050036
			public static int blue = 2131034166;
			
			// aapt resource value: 0x7f05000f
			public static int bottomactionbar_background_end = 2131034127;
			
			// aapt resource value: 0x7f050010
			public static int bottomactionbar_background_item_pressed_end = 2131034128;
			
			// aapt resource value: 0x7f050011
			public static int bottomactionbar_background_item_pressed_start = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public static int bottomactionbar_background_start = 2131034126;
			
			// aapt resource value: 0x7f050027
			public static int bottomactionbar_maincolor_black = 2131034151;
			
			// aapt resource value: 0x7f05002f
			public static int bottomactionbar_maincolor_blue = 2131034159;
			
			// aapt resource value: 0x7f05001f
			public static int bottomactionbar_maincolor_darkgray = 2131034143;
			
			// aapt resource value: 0x7f050017
			public static int bottomactionbar_maincolor_lightgray = 2131034135;
			
			// aapt resource value: 0x7f050028
			public static int bottomactionbar_pressedcolor_black = 2131034152;
			
			// aapt resource value: 0x7f050030
			public static int bottomactionbar_pressedcolor_blue = 2131034160;
			
			// aapt resource value: 0x7f050020
			public static int bottomactionbar_pressedcolor_darkgray = 2131034144;
			
			// aapt resource value: 0x7f050018
			public static int bottomactionbar_pressedcolor_lightgray = 2131034136;
			
			// aapt resource value: 0x7f05000c
			public static int bottomactionbar_separator = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public static int bottomactionbar_title = 2131034125;
			
			// aapt resource value: 0x7f050034
			public static int green = 2131034164;
			
			// aapt resource value: 0x7f050037
			public static int grey = 2131034167;
			
			// aapt resource value: 0x7f050029
			public static int pager_black = 2131034153;
			
			// aapt resource value: 0x7f050031
			public static int pager_blue = 2131034161;
			
			// aapt resource value: 0x7f050021
			public static int pager_darkgray = 2131034145;
			
			// aapt resource value: 0x7f050019
			public static int pager_lightgray = 2131034137;
			
			// aapt resource value: 0x7f050035
			public static int red = 2131034165;
			
			// aapt resource value: 0x7f050032
			public static int white = 2131034162;
			
			// aapt resource value: 0x7f050038
			public static int yellow = 2131034168;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public static int actionbar_accentheight = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int actionbar_height = 2131099649;
			
			// aapt resource value: 0x7f060005
			public static int actionbar_home_item_width = 2131099653;
			
			// aapt resource value: 0x7f060002
			public static int actionbar_item_height = 2131099650;
			
			// aapt resource value: 0x7f060006
			public static int actionbar_item_height_over = 2131099654;
			
			// aapt resource value: 0x7f060003
			public static int actionbar_item_height_overflow = 2131099651;
			
			// aapt resource value: 0x7f060004
			public static int actionbar_item_width = 2131099652;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int actionbar_back_indicator_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int actionbar_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int actionbar_background_alt = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int actionbar_background_black = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int actionbar_background_blue = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int actionbar_background_darkgray = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int actionbar_background_lightgray = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int actionbar_btn = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int actionbar_btn_alt = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int actionbar_btn_black = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int actionbar_btn_blue = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int actionbar_btn_darkgray = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int actionbar_btn_lightgray = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int actionbar_btn_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int actionbar_btn_normal_alt = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int actionbar_btn_pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int actionbar_btn_pressed_alt = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int bottomactionbar_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int bottomactionbar_background_black = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int bottomactionbar_background_blue = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int bottomactionbar_background_darkgray = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int bottomactionbar_background_lightgray = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int bottomactionbar_btn = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int bottomactionbar_btn_black = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int bottomactionbar_btn_blue = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int bottomactionbar_btn_darkgray = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int bottomactionbar_btn_lightgray = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int bottomactionbar_btn_normal = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public static int bottomactionbar_btn_pressed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int ic_action_overflow = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int ic_action_overflow_dark = 2130837535;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000b
			public static int actionbar_actions = 2130968587;
			
			// aapt resource value: 0x7f040006
			public static int actionbar_home = 2130968582;
			
			// aapt resource value: 0x7f040008
			public static int actionbar_home_bg = 2130968584;
			
			// aapt resource value: 0x7f040009
			public static int actionbar_home_btn = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public static int actionbar_home_is_back = 2130968586;
			
			// aapt resource value: 0x7f040007
			public static int actionbar_home_logo = 2130968583;
			
			// aapt resource value: 0x7f04000f
			public static int actionbar_item = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public static int actionbar_progress = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public static int actionbar_title = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public static int actionbar_title_layout = 2130968588;
			
			// aapt resource value: 0x7f040000
			public static int custom = 2130968576;
			
			// aapt resource value: 0x7f040003
			public static int holo_black = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int holo_blue = 2130968580;
			
			// aapt resource value: 0x7f040002
			public static int holo_gray = 2130968578;
			
			// aapt resource value: 0x7f040001
			public static int holo_light = 2130968577;
			
			// aapt resource value: 0x7f040010
			public static int overflow_spinner = 2130968592;
			
			// aapt resource value: 0x7f040005
			public static int screen = 2130968581;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int actionbar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int actionbar_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int blankspinner = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int overflowactionbar_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int spinneritem = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public static int actionbar_activity_not_found = 2131165184;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public static int actionbar = 2131230720;
			
			// aapt resource value: 0x7f080003
			public static int actionbarhomeitem = 2131230723;
			
			// aapt resource value: 0x7f080004
			public static int actionbarhomelogo = 2131230724;
			
			// aapt resource value: 0x7f080001
			public static int actionbaritem = 2131230721;
			
			// aapt resource value: 0x7f080005
			public static int actionbarprogressbar = 2131230725;
			
			// aapt resource value: 0x7f080002
			public static int clearbutton = 2131230722;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] actionbar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 3
			public static int actionbar_background = 3;
			
			// aapt resource value: 4
			public static int actionbar_background_item = 4;
			
			// aapt resource value: 6
			public static int actionbar_is_bottom = 6;
			
			// aapt resource value: 7
			public static int actionbar_light_icons = 7;
			
			// aapt resource value: 2
			public static int actionbar_separator = 2;
			
			// aapt resource value: 5
			public static int actionbar_theme = 5;
			
			// aapt resource value: 0
			public static int actionbar_title = 0;
			
			// aapt resource value: 1
			public static int actionbar_title_color = 1;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
